export default [
  "hi",
  ":3",
  "...",
  "pretty bad.",
  "uwu",
  "I got fucked over",
  "relationship wise",
  "hhh",
  "ok do you",
  "mind if I vent",
  "ok well",
  "this guy yeah",
  "I liked him a lot",
  "he said he was also interested",
  "but one time I told him I erpd with someone else and like",
  "he said his feelings were hurt so",
  "i like",
  "committed to him",
  "didn't do stuff with anyone else yknow",
  "so um... this weekend I went to TwitchCon to come see him",
  "that was literally the only reason I went",
  "we hung out",
  "it was cool",
  "he ended up in my hotel room for a bit and",
  "he did me",
  "but he couldn't stay because he has a roommate who is staying with him in his room",
  "it's his costreamer",
  "anyway that was",
  "good",
  "uh",
  "the next day he got sick and wasn't with us",
  "I overheard his co",
  "and um",
  "he has",
  "a wife",
  "um",
  "that's not the worst of it",
  "I tried talking to him about it",
  "because like",
  "things can be ok right",
  "image:Screenshot_2018-10-29-01-00-59.png",
  "image:Screenshot_2018-10-29-01-01-27.png",
  "so like",
  "I wasn't getting answers from him",
  "even though he's",
  "like 30 something",
  "just immature",
  "w/e",
  "but I pulled his co into a private chat",
  "And told him he couldn't tell anyone",
  "but",
  "I had to just get it off my chest because the guy was just blocking me off",
  "I told his co that we did things",
  "sent screens to confirm",
  "and his co was like oh it's ok if it makes you feel any better his relationship isn't going too great",
  "which didn't super make me feel better but I appreciated the thought yknow",
  "but we'll",
  "well*",
  "after a bit",
  "his co had",
  "something to tell me",
  "is that",
  "he also liked the guy",
  "so that complicates things",
  "futhermore",
  "that same night",
  "the guy fucked both of us",
  "his co right after me",
  "didn't tell either of us",
  "but his co said they had an agreement to be open as long as they told each other about it",
  "but the guy didn't tell his co about me",
  "and",
  "it's just been a trip",
  "his co ended up breaking down in front of the guy and slipped that I sent logs",
  "image:Screenshot_2018-10-29-01-06-17.png",
  "it's just",
  "a fucking trip",
  "he's been blaming me for sending logs",
  "he blocked me from everything",
  "told his co i can't talk to him",
  "and i just want to talk it out but",
  "I guess that's not happening",
  "it literally could not have been any fucking worse",
  "not only that",
  "I donated thousands to him",
  "and dropped about another thousand and my weekend just to see him at the con ",
  "and I have a fucking exam tomorrow",
  "I just",
  "feel so used",
  "....",
  "I thought he was for real",
  "I dropped everything for him",
  "... yeah",
  "I'm glad it happened though",
  "he's",
  "... bad.",
  "but",
  "he had called me an abuser for proposing a poly relationship in the past",
  "I don't know anymore",
  "ugjgjgjk",
  "I wouldn't even like hold it against him",
  "he just refuses to talk to me",
  "if he would just be straightforward",
  "...",
  "I guess it doesn't matter",
  "he got what he wanted",
  "I guess",
  "pff",
  "his life will be fine",
  "he didn't get nothin bad out of it",
  "his co has no choice bc he works for the guy and has no other job",
  "so",
  "co has to do what he says",
  "even",
  "not talking to me",
  "I guess",
  "it's hard to forget",
  "so",
  "I dunno",
  "sorry to drop that all on you",
  "hh",
  "I just feel fucking",
  "used",
  "how could anyone do this",
  "it's so unreal",
  "it literally feels abstract to me right now",
  "he was like",
  "my plan",
  "I was super committed",
  "and he just used me",
  "and I have an exam tomorrow",
  "that I couldn't study for",
  ": ^)",
  "y'know",
  "on top of all of this",
  "I removed all my body hair for him",
  'because he likes "smooth"',
  "razor went bad so I ended up plucking every one of my hairs with fucking tweezers for him",
  "sorry if that's tmi",
  "but it took three fucking days",
  "three",
  "painful",
  "days",
  "I just want to cry",
  "in the end nothing mattered to him...",
  "he doesn't care about me in the slightest......",
  "he made a point of never telling me that he loved me",
  "... yeah",
];
